// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: url/url.proto

package url

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Url_Create_FullMethodName = "/Url/Create"
)

// UrlClient is the client API for Url service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrlClient interface {
	Create(ctx context.Context, in *CreateUrlRequest, opts ...grpc.CallOption) (*CreateUrlResponse, error)
}

type urlClient struct {
	cc grpc.ClientConnInterface
}

func NewUrlClient(cc grpc.ClientConnInterface) UrlClient {
	return &urlClient{cc}
}

func (c *urlClient) Create(ctx context.Context, in *CreateUrlRequest, opts ...grpc.CallOption) (*CreateUrlResponse, error) {
	out := new(CreateUrlResponse)
	err := c.cc.Invoke(ctx, Url_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlServer is the server API for Url service.
// All implementations must embed UnimplementedUrlServer
// for forward compatibility
type UrlServer interface {
	Create(context.Context, *CreateUrlRequest) (*CreateUrlResponse, error)
	mustEmbedUnimplementedUrlServer()
}

// UnimplementedUrlServer must be embedded to have forward compatible implementations.
type UnimplementedUrlServer struct {
}

func (UnimplementedUrlServer) Create(context.Context, *CreateUrlRequest) (*CreateUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUrlServer) mustEmbedUnimplementedUrlServer() {}

// UnsafeUrlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrlServer will
// result in compilation errors.
type UnsafeUrlServer interface {
	mustEmbedUnimplementedUrlServer()
}

func RegisterUrlServer(s grpc.ServiceRegistrar, srv UrlServer) {
	s.RegisterService(&Url_ServiceDesc, srv)
}

func _Url_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Url_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlServer).Create(ctx, req.(*CreateUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Url_ServiceDesc is the grpc.ServiceDesc for Url service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Url_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Url",
	HandlerType: (*UrlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Url_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "url/url.proto",
}
