version: '3.8'
services:
  shortener-service:
    image: shortener-service
    container_name: shortener-service
    build:
      context: ./shortener
      dockerfile: Dockerfile
      target: shortener-service
    ports:
      - '50051/tcp'
    environment:
        - APPLICATION_PORT=50051
        - DATA_SOURCE_URL=mongodb://fupitz:12345678@mongodb:27017/fupitz?authMechanism=SCRAM-SHA-1
        - KEYGEN_SERVICE_URL=keygen-service:50052
        - ENV=development
    depends_on:
      - mongodb
      - keygen-service
  keygen-service:
    image: keygen-service
    container_name: keygen-service
    build:
      context: ./keygen
      dockerfile: Dockerfile
    ports:
      - '50052:50052'
    environment:
        - APPLICATION_PORT=50052
        - DATA_SOURCE_URL=mongodb://fupitz:12345678@mongodb:27017/fupitz?authMechanism=SCRAM-SHA-1
        - ENV=development
    depends_on:
      - mongodb
  gateway-service:
    image: gateway-service
    container_name: gateway-service
    build:
      context: ./shortener
      dockerfile: Dockerfile
      target: gateway-service
      args:
        SHORTENER_SERVICE_ADDRESS: shortener-service:50051
    ports:
      - '8080:8080'
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
volumes:
  mongodb_data: