// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: keygen/keygen.proto

package keygen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Keygen_Generate_FullMethodName = "/Keygen/Generate"
)

// KeygenClient is the client API for Keygen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeygenClient interface {
	Generate(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error)
}

type keygenClient struct {
	cc grpc.ClientConnInterface
}

func NewKeygenClient(cc grpc.ClientConnInterface) KeygenClient {
	return &keygenClient{cc}
}

func (c *keygenClient) Generate(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error) {
	out := new(GenerateKeyResponse)
	err := c.cc.Invoke(ctx, Keygen_Generate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeygenServer is the server API for Keygen service.
// All implementations must embed UnimplementedKeygenServer
// for forward compatibility
type KeygenServer interface {
	Generate(context.Context, *GenerateKeyRequest) (*GenerateKeyResponse, error)
	mustEmbedUnimplementedKeygenServer()
}

// UnimplementedKeygenServer must be embedded to have forward compatible implementations.
type UnimplementedKeygenServer struct {
}

func (UnimplementedKeygenServer) Generate(context.Context, *GenerateKeyRequest) (*GenerateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedKeygenServer) mustEmbedUnimplementedKeygenServer() {}

// UnsafeKeygenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeygenServer will
// result in compilation errors.
type UnsafeKeygenServer interface {
	mustEmbedUnimplementedKeygenServer()
}

func RegisterKeygenServer(s grpc.ServiceRegistrar, srv KeygenServer) {
	s.RegisterService(&Keygen_ServiceDesc, srv)
}

func _Keygen_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeygenServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keygen_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeygenServer).Generate(ctx, req.(*GenerateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Keygen_ServiceDesc is the grpc.ServiceDesc for Keygen service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Keygen_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Keygen",
	HandlerType: (*KeygenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _Keygen_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keygen/keygen.proto",
}
