// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: clicks/clicks.proto

package clicks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SaveClicks_CreateUrlClick_FullMethodName = "/SaveClicks/CreateUrlClick"
)

// SaveClicksClient is the client API for SaveClicks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaveClicksClient interface {
	CreateUrlClick(ctx context.Context, in *UrlClickRequest, opts ...grpc.CallOption) (*UrlClickResponse, error)
}

type saveClicksClient struct {
	cc grpc.ClientConnInterface
}

func NewSaveClicksClient(cc grpc.ClientConnInterface) SaveClicksClient {
	return &saveClicksClient{cc}
}

func (c *saveClicksClient) CreateUrlClick(ctx context.Context, in *UrlClickRequest, opts ...grpc.CallOption) (*UrlClickResponse, error) {
	out := new(UrlClickResponse)
	err := c.cc.Invoke(ctx, SaveClicks_CreateUrlClick_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaveClicksServer is the server API for SaveClicks service.
// All implementations must embed UnimplementedSaveClicksServer
// for forward compatibility
type SaveClicksServer interface {
	CreateUrlClick(context.Context, *UrlClickRequest) (*UrlClickResponse, error)
	mustEmbedUnimplementedSaveClicksServer()
}

// UnimplementedSaveClicksServer must be embedded to have forward compatible implementations.
type UnimplementedSaveClicksServer struct {
}

func (UnimplementedSaveClicksServer) CreateUrlClick(context.Context, *UrlClickRequest) (*UrlClickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUrlClick not implemented")
}
func (UnimplementedSaveClicksServer) mustEmbedUnimplementedSaveClicksServer() {}

// UnsafeSaveClicksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaveClicksServer will
// result in compilation errors.
type UnsafeSaveClicksServer interface {
	mustEmbedUnimplementedSaveClicksServer()
}

func RegisterSaveClicksServer(s grpc.ServiceRegistrar, srv SaveClicksServer) {
	s.RegisterService(&SaveClicks_ServiceDesc, srv)
}

func _SaveClicks_CreateUrlClick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UrlClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaveClicksServer).CreateUrlClick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaveClicks_CreateUrlClick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaveClicksServer).CreateUrlClick(ctx, req.(*UrlClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaveClicks_ServiceDesc is the grpc.ServiceDesc for SaveClicks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaveClicks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SaveClicks",
	HandlerType: (*SaveClicksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUrlClick",
			Handler:    _SaveClicks_CreateUrlClick_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clicks/clicks.proto",
}
