// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: redirect/redirect.proto

package redirect

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Redirect_Redirect_FullMethodName = "/Redirect/Redirect"
)

// RedirectClient is the client API for Redirect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedirectClient interface {
	Redirect(ctx context.Context, in *RedirectRequest, opts ...grpc.CallOption) (*RedirectResponse, error)
}

type redirectClient struct {
	cc grpc.ClientConnInterface
}

func NewRedirectClient(cc grpc.ClientConnInterface) RedirectClient {
	return &redirectClient{cc}
}

func (c *redirectClient) Redirect(ctx context.Context, in *RedirectRequest, opts ...grpc.CallOption) (*RedirectResponse, error) {
	out := new(RedirectResponse)
	err := c.cc.Invoke(ctx, Redirect_Redirect_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedirectServer is the server API for Redirect service.
// All implementations must embed UnimplementedRedirectServer
// for forward compatibility
type RedirectServer interface {
	Redirect(context.Context, *RedirectRequest) (*RedirectResponse, error)
	mustEmbedUnimplementedRedirectServer()
}

// UnimplementedRedirectServer must be embedded to have forward compatible implementations.
type UnimplementedRedirectServer struct {
}

func (UnimplementedRedirectServer) Redirect(context.Context, *RedirectRequest) (*RedirectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Redirect not implemented")
}
func (UnimplementedRedirectServer) mustEmbedUnimplementedRedirectServer() {}

// UnsafeRedirectServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedirectServer will
// result in compilation errors.
type UnsafeRedirectServer interface {
	mustEmbedUnimplementedRedirectServer()
}

func RegisterRedirectServer(s grpc.ServiceRegistrar, srv RedirectServer) {
	s.RegisterService(&Redirect_ServiceDesc, srv)
}

func _Redirect_Redirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedirectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedirectServer).Redirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Redirect_Redirect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedirectServer).Redirect(ctx, req.(*RedirectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Redirect_ServiceDesc is the grpc.ServiceDesc for Redirect service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Redirect_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Redirect",
	HandlerType: (*RedirectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Redirect",
			Handler:    _Redirect_Redirect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redirect/redirect.proto",
}
